# Core source files
SET( FUTSIM_CORE_SOURCE )

# Core internal headers
SET( FUTSIM_CORE_INTERNAL_HEADERS )

# Core external headers
SET( FUTSIM_CORE_EXTERNAL_HEADERS )

# Source files
SET( FUTSIM_SOURCE ${FUTSIM_CORE_SOURCE} )

# Internal headers
SET( FUTSIM_INTERNAL_HEADERS ${FUTSIM_CORE_INTERNAL_HEADERS} )

# External headers
SET( FUTSIM_EXTERNAL_HEADERS ${FUTSIM_CORE_EXTERNAL_HEADERS} )