SET(FUTSIM_TESTS_ENGINE_SOURCE
	ATest.cpp)

SET(FUTSIM_TESTS_UNIT_CORE_SOURCE
	unit/TEnumDistribution.cpp
	unit/TPerson.cpp
	unit/TPlayTime.cpp
)

SET(FUTSIM_TESTS_UNIT_FOOTBALL_SOURCE
	unit/football/TExtraTime.cpp
	unit/football/TChancesDrawConfiguration.cpp
	unit/football/TChanceState.cpp
	unit/football/TDrawConfiguration.cpp
	unit/football/TFoulDrawConfiguration.cpp
	unit/football/TFoulState.cpp
	unit/football/TGoalDrawConfiguration.cpp
	unit/football/TLineup.cpp
	unit/football/TLineupConfiguration.cpp
	unit/football/TMatch.cpp
	unit/football/TMatchConfiguration.cpp
	unit/football/TMatchState.cpp
	unit/football/TTeamStrategy.cpp
	unit/football/TPenaltyShootoutConfiguration.cpp
	unit/football/TPenaltyShootoutState.cpp
	unit/football/TPenaltyState.cpp
	unit/football/TPeriodState.cpp
	unit/football/TPeriodStates.cpp
	unit/football/TPlayer.cpp
	unit/football/TPlayerSkills.cpp
	unit/football/TPlayState.cpp
	unit/football/TPlayTime.cpp
	unit/football/TPossessionDrawConfiguration.cpp
	unit/football/TPossessionState.cpp
	unit/football/TStadium.cpp
	unit/football/TTacticConfiguration.cpp
	unit/football/TTacticsConfiguration.cpp
	unit/football/TTeam.cpp
	unit/football/TTieCondition.cpp
)